backend:
  name: git-gateway
  branch: main 

media_folder: "src/img"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    extension: "json"
    format: "json"
    folder: data
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { name: title }
      - { name: desc }